-- 트랜잭션 시작
START TRANSACTION;

-- UsedTrade 테이블에 시간 필드 추가
ALTER TABLE usedTrade 
ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- UsedPay 테이블에 결제 상세 정보 필드 추가
ALTER TABLE usedPay 
ADD COLUMN paymentKey VARCHAR(100),
ADD COLUMN orderId VARCHAR(100),
ADD COLUMN totalAmount INT,
ADD COLUMN cashAmount INT,
ADD COLUMN pointAmount INT,
ADD COLUMN cardAmount INT,
ADD COLUMN paymentMethod VARCHAR(20),
ADD COLUMN status INT DEFAULT 0,
ADD COLUMN receiptUrl VARCHAR(500),
ADD COLUMN qrUrl VARCHAR(500),
ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN approvedAt TIMESTAMP;

-- 트랜잭션 커밋
COMMIT;
