-- Flyway V36 - customer 테이블 기본값 추가
ALTER TABLE customer
    MODIFY COLUMN cash INT DEFAULT 0 NOT NULL,
    MODIFY COLUMN totalPrice INT DEFAULT 0 NOT NULL,
    MODIFY COLUMN point INT DEFAULT 0 NOT NULL,
    MODIFY COLUMN status INT DEFAULT 0 NOT NULL;