CREATE TABLE hotelDraft (
    draftIdx INT AUTO_INCREMENT PRIMARY KEY,
    adminIdx INT NOT NULL UNIQUE,
    formData JSON,
    lastTab VARCHAR(50),
    progress INT DEFAULT 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (adminIdx) REFERENCES admin(adminIdx) ON DELETE CASCADE
);